[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/psi4manual/master/*"
  to = "https://psi4manual.netlify.app/:splat"
  status = 200
  force = true

