[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/psi4manual/master/*"
  #to = "https://psi4manual.netlify.app/:splat"
  #to = "https://molssi.github.io/QCElemental/:splat"
  to = "https://psi4.github.io/psi4docs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/downloads*"
  to = "/installs/latest"
  status = 301
